### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by vidhwanshak** [Tran-Antoine/sphinx#68]
Please update the docs. No information present on how can i download this application on my system.

**Comment by Tran-Antoine** [comment]
Hello and welcome to the Sphinx respository!
Since the contributors agreed that the projet is not ready yet for an "official" release, you can currently only add the project as a dependency via gradle and services like jitpack (you would need to target the master). If you wish to contribute though, all you need to do is clone the repository and make pull requests. The wiki will in the future contain resources to explain how the API internally works, for now unfortunately there is nothing else than the javadocs (which is incomplete). For now all there is is a getting started explaining how to use the API. However if you have specific questions about how it works, feel free to either ask them here or to send me an email (antoine.tran@epfl.ch).

Note that Sphinx is not a program in itself that can be run, it's an API for developers who wish to add quizzes to their own program. There is a current implementation that's the discord bot, which is present under the discord-impl folder

**Comment by Tran-Antoine** [comment]
If you are looking for a sample program that demonstrates how to use the API, you can check an example here: https://github.com/Tran-Antoine/sphinx/tree/samples/samples/src/main/java/helloquiz
